//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int id_goods { get; set; }
        public string name_goods { get; set; }
        public string price { get; set; }
        public string description { get; set; }
        public string img { get; set; }
        public string sale { get; set; }
    }
}
